#32 связать базу данных и словарь
Aprekek/Timetable pull request #54
Opened 2021-01-08 11:34 UTC by Aprekek

2021-01-08 14:02 UTC, FEvgenSON requested changes

2021-01-08 14:02 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryViewModel.kt
> +
тут пустая строчка?

2021-01-08 14:02 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryViewModel.kt
> +        Categories.SUBJECT_CATEGORY -> getAllSubjectsFlowUseCase()
сделай enumом

2021-01-08 14:02 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryViewModel.kt
> +    val listCategoryItemsLiveData = when (categoryType) {
Из этого можно сделать сценарий, который как раз вернет твою новую модель, тогда все пред изменения не нужны

2021-01-08 14:02 UTC, FEvgenSON commented on features/lessoncreate/src/main/java/ru/fevgenson/timetable/features/lessoncreate/domain/usecase/GetClassroomsValuesUseCase.kt
> +        repository.getAllClassrooms().map { it.description }
То есть все коммиты ниже даже не собираются, каеф

2021-01-09 07:44 UTC, FEvgenSON requested changes

2021-01-09 07:44 UTC, FEvgenSON commented on shared/lesson/data/src/main/java/ru/fevgenson/timetable/shared/lesson/data/mapper/SubcategoryMapper.kt
> +package ru.fevgenson.timetable.shared.lesson.data.mapper
А давай он будет лежать только в твоем модуле, так как больше нигде не планируется использовать этот класс

2021-01-09 07:44 UTC, FEvgenSON commented on features/dictionary/build.gradle.kts
> +    implementation(project(Modules.Shared.Lesson.DATA))
А зачем тебе тут дата слой

2021-01-09 07:44 UTC, FEvgenSON commented on shared/lesson/domain/src/main/java/ru/fevgenson/timetable/shared/lesson/domain/entity/CategoryEntity.kt
> +    fun toSubcategoryEntity(): SubcategoryEntity
Зачем? Ты в прошлом коммите сделал мапперы

2021-01-09 07:44 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/di/DictionaryModule.kt
> +        PageCategoryViewModel(get(), categoryType, parentViewModel)
давай исеннованные

2021-01-09 07:44 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +    operator fun invoke(category: Categories.CategoryTypes): Flow<List<SubcategoryEntity>> =
Пустую строчку

2021-01-09 07:44 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
Если в пред коммите ты сделал интерфейс для этого, то можно просто вызывать мап прямо в when, тогда тот интерфейс будет не нужен

2021-01-09 07:44 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryViewModel.kt
> +        getListOfSubcategoriesScenario(categoryType).flowOn(Dispatchers.IO).asLiveData()
flowOn ставился на слое repository, тут он не нужен

2021-01-09 08:05 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
Так ты сделай extention для list, если особо горит можешь и для flow, будет просто по еще одному вызову на строчку. А так опять ты переделываешь домейн

2021-01-09 08:05 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/di/DictionaryModule.kt
> +        PageCategoryViewModel(get(), categoryType, parentViewModel)
именованные*

2021-01-09 08:10 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
у меня и так теперь jeneric extemtion на list стоит, а без интерфейса придется какое-то говно с  jvmName мутить, либо 5 разных extention под каждую категорию

2021-01-09 08:20 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
у тебя и так есть 5 разных extention и это норм тема

2021-01-09 08:26 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
для листа у меня 1 extention, а там мне придется 5 ручками писать

2021-01-09 08:27 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
просто чем тебя не устраивает этот вариант?

2021-01-09 08:27 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/domain/scenario/GetListOfSubcategoriesScenario.kt
> +        }.map { list -> list.map { it.toSubcategoryEntity() } }
![image](https://user-images.githubusercontent.com/24730141/104087017-38b32e80-528f-11eb-8e1d-307a58c14acc.png)

2021-01-09 09:30 UTC, FEvgenSON approved these changes

2021-01-09 16:34 UTC, merged