#46 перевести dictionary на flow
Aprekek/Timetable pull request #58
Opened 2021-02-01 08:15 UTC by Aprekek

Дополнительно: resolve #47 "добавить категорию type в Dictionary"

2021-02-01 12:21 UTC, FEvgenSON requested changes

2021-02-01 12:21 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/recyclerview/CategoryItemViewHolder.kt
> +    private lateinit var subcategoryDescription: String
`lateinit var` мне категорически не нравятся, можно как-нибудь по другому?

2021-02-01 12:21 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/recyclerview/CategoryItemViewHolder.kt
> +    private lateinit var subcategoryDescription: String
Он тут в принципе не нужен, если ты добавил его для лямбды, то там хватит и аргумента, который приходит в метод

2021-02-01 12:21 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryDelegate.kt
> +        if (!it.isNullOrEmpty()) null else R.string.dictionary_no_items
`R.string.dictionary_no_items.takeIf{ !items.isNullOrEmpty() }`

2021-02-01 12:21 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryViewHolder.kt
> +            lifecycleOwner.lifecycleScope
давай сюда сразу скоуп тащить, зачем тут овнер. + у нас есть екстеншн для фрагмента, который сразу скоуп дает

2021-02-01 12:21 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/DictionaryFragment.kt
> +    private fun TabLayout.setTabMargins(
А без этого никак? На главной полностью кастомные табы и там обошлись без этого

2021-02-01 13:33 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryDelegate.kt
> +        if (!it.isNullOrEmpty()) null else R.string.dictionary_no_items
Вкусовщина

2021-02-01 13:34 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/DictionaryFragment.kt
> +    private fun TabLayout.setTabMargins(
ты там сам создавал табы, тут я просто поменял отступы

2021-02-01 13:48 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/viewpager/PageCategoryDelegate.kt
> +        if (!it.isNullOrEmpty()) null else R.string.dictionary_no_items
Нет, это использование синтаксиса языка по назначению. Эта штука специально сделана на замену такому типу if

2021-02-01 13:49 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/DictionaryFragment.kt
> +    private fun TabLayout.setTabMargins(
А в верстке нельзя менять отступы у таба? И зачем вообще менять отступы? Можно скрин?

2021-02-01 14:04 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/DictionaryFragment.kt
> +    private fun TabLayout.setTabMargins(
Там только падинг можно у табов менять. А так без отступов выглядит 
![image](https://user-images.githubusercontent.com/47656911/106468807-fcab6c00-64d0-11eb-88ab-0c1d35c402c5.png)

2021-02-02 12:36 UTC, FEvgenSON commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/DictionaryFragment.kt
> +    private fun TabLayout.setTabMargins(
А что по цветам, мы же договаривались поменять черный. Или это не в этом пуле?

2021-02-02 12:52 UTC, Aprekek commented on features/dictionary/src/main/java/ru/fevgenson/timetable/features/dictionary/presentation/dictionary/DictionaryFragment.kt
> +    private fun TabLayout.setTabMargins(
да в принципе можно и в этом поменять, на какой мы договаривались? Серый?

2021-02-02 13:13 UTC, FEvgenSON approved these changes

2021-02-02 13:14 UTC, merged